### PR TITLE
[#168] Fix draw detection when all remaining players loose in the same round

### PR DESCRIPTION
**Pull request by flamion**

### CODE REVIEW

**Comment by nikkischnelle** [comment]
> > I'd like to see tests, that show me that the internal shork doesn't just output a Draw for everything. Only the draw-situation is covered by tests rn and non-draw-situations aren't
> 
> They weren't in the scope of the story, but I can add them

We can also add them later on, if you'd rather merge this now and do that later

**Comment by flamion** [comment]
> > > I'd like to see tests, that show me that the internal shork doesn't just output a Draw for everything. Only the draw-situation is covered by tests rn and non-draw-situations aren't
> > 
> > 
> > They weren't in the scope of the story, but I can add them
> 
> We can also add them later on, if you'd rather merge this now and do that later

I can just quickly add them, shouldn't take long. However, if they fail, fixing would be a separate story

**Comment by nikkischnelle** [comment]
> > > > I'd like to see tests, that show me that the internal shork doesn't just output a Draw for everything. Only the draw-situation is covered by tests rn and non-draw-situations aren't
> > > 
> > > 
> > > They weren't in the scope of the story, but I can add them
> > 
> > 
> > We can also add them later on, if you'd rather merge this now and do that later
> 
> I can just quickly add them, shouldn't take long. However, if they fail, fixing would be a separate story

That would lead to the main deployment not being up-to-date until they are fixed.
Not something we should do.

**Comment by flamion** [comment]
> > > > > I'd like to see tests, that show me that the internal shork doesn't just output a Draw for everything. Only the draw-situation is covered by tests rn and non-draw-situations aren't
> > > > 
> > > > 
> > > > They weren't in the scope of the story, but I can add them
> > > 
> > > 
> > > We can also add them later on, if you'd rather merge this now and do that later
> > 
> > 
> > I can just quickly add them, shouldn't take long. However, if they fail, fixing would be a separate story
> 
> That would lead to the main deployment not being up-to-date until they are fixed. Not something we should do.

Test has been added.

**Pull request merged**
