### PR TITLE
#99 Run Unit Tests as Pre-Push hook

### PR DESCRIPTION
**Pull request by nikkischnelle**
Please also test on Windows :)
It shouldn't actually RUN the tests on push, if nothing has changed in the frontend dir for the frontend tests and backend dir for backend tests.
To try out whether the hooks run or not:

```
pre-commit run --hook-stage push -a test-backend
pre-commit run --hook-stage push -a test-frontend
```

### CODE REVIEW

**Review by 0815Sailsman — CHANGES_REQUESTED** [review]
Frontend tests work
Backend test don't:

```
pre-commit run --hook-stage push -a test-backend
[WARNING] hook id `test-backend` uses deprecated stage names (push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
[WARNING] hook id `test-frontend` uses deprecated stage names (push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
Run backend tests........................................................Failed
- hook id: test-backend
- exit code: 1

Running gradle task: test
Traceback (most recent call last):
  File "C:\Users\danie\IdeaProjects\corewar\scripts\run_gradle.py", line 29, in <module>
    run_gradle()
  File "C:\Users\danie\IdeaProjects\corewar\scripts\run_gradle.py", line 24, in run_gradle
    subprocess.run("ls")
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

Maybe because it tries to run `ls` which is not available on windows?

**Comment by nikkischnelle** [comment]
> Frontend tests work Backend test don't:
> 
> ```
> pre-commit run --hook-stage push -a test-backend
> [WARNING] hook id `test-backend` uses deprecated stage names (push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
> [WARNING] hook id `test-frontend` uses deprecated stage names (push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
> Run backend tests........................................................Failed
> - hook id: test-backend
> - exit code: 1
> 
> Running gradle task: test
> Traceback (most recent call last):
>   File "C:\Users\danie\IdeaProjects\corewar\scripts\run_gradle.py", line 29, in <module>
>     run_gradle()
>   File "C:\Users\danie\IdeaProjects\corewar\scripts\run_gradle.py", line 24, in run_gradle
>     subprocess.run("ls")
>   File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
> ```
> 
> Maybe because it tries to run `ls` which is not available on windows?

I used that to debug and forgot about it being there :sweat_smile:

**Review by 0815Sailsman — COMMENTED** [review]
Now everything seems to work, but there is no console output at all about what is happening. Is it possible to somehow display the test status while they are running and / or the test results after they are finished?

**Comment by nikkischnelle** [comment]
> Now everything seems to work, but there is no console output at all about what is happening. Is it possible to somehow display the test status while they are running and / or the test results after they are finished?

There is now output if the hook fails. This is the default behavior for pre-commit, and I don't think it's easily changed.
But only showing output if the tests fail should be fine, right?

**Review by freuwoert — APPROVED** [review]
Correct feedback is given:
```bash
$ pre-commit run --hook-stage push -a test-frontend
Frontend Tests...........................................................Passed
```
```bash
$ pre-commit run --hook-stage push -a test-backend
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Run backend tests........................................................Passed
```
Just giving an indication if they fail should suffice.
LGTM

**Review by 0815Sailsman — APPROVED** [review]
what @freuwoert said

**Pull request merged**
