### PR TITLE
180 fe vscode browser integration

### PR DESCRIPTION
**Pull request by Straczi**

### CODE REVIEW

**Comment by Straczi** [comment]
not open for review yet, just to easily see changes, reviewer will be assigned once done

**Comment by flamion** [comment]
> not open for review yet, just to easily see changes, reviewer will be assigned once done

You could make the PR a draft PR for that case :D

**Comment by Straczi** [comment]
> > not open for review yet, just to easily see changes, reviewer will be assigned once done
> 
> You could make the PR a draft PR for that case :D

whoopsies, will do that in future :point_right: :point_left:

**Review by nikkischnelle — COMMENTED** [review]
infra stuff lgtm

**Pull request closed without merging**
