### PR TITLE
276 modify api spec to handle visualization data

### PR DESCRIPTION
**Pull request by flamion**

### CODE REVIEW

**Review by 0815Sailsman — CHANGES_REQUESTED** [review]
Please add a reference to the gamedata planning file in the apiv1.md and cleanup that file. I don't think this is easily understood by someone who has not partaken in the original planning meeting.

I'd suggest cleanly rewriting the gamedata spec file to explain what data we collect, where it gets collect, and more. Atm I feel like its an unstructured mess (that I wrote 😵 )

**Comment by flamion** [comment]
Yes, the gamedata.txt is currently just a collection of thoughts from that meeting. I'd have expected it to just get deleted once the visualization is done / implemented

**Comment by flamion** [comment]
So I should add something like a `gamedata.md` that explains what we collect, and why?

**Review by 0815Sailsman — APPROVED** [review]
yeah seems good

**Pull request merged**
